markdown:       kramdown
kramdown:
  auto_ids:     true
encoding:       UTF-8
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
sass:
  sass_dir: ./
  style: compressed

theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag

title: "my site"

twitter:
  username: arpitingle


